# Generated by Django 3.0 on 2019-12-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_delete_likeship'),
        ('users', '0003_user_like_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_r',
            field=models.ManyToManyField(db_table='UserFavoriteVideo', to='video.Video'),
        ),
    ]
