# Generated by Django 3.0 on 2020-03-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20200328_1325'),
        ('users', '0005_auto_20191223_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_r',
            field=models.ManyToManyField(blank=True, db_table='UserFavoriteVideo', related_name='viewer', to='video.Video'),
        ),
    ]
