# Generated by Django 3.0 on 2020-03-28 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Director',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('cover', models.CharField(blank=True, max_length=500, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('brief', models.TextField(blank=True, default=None, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('view_count', models.IntegerField(blank=True, default=0)),
                ('episode', models.PositiveIntegerField(blank=True, null=True)),
                ('animename', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('videos', models.ManyToManyField(blank=True, db_table='TypeToVideo', related_name='type', to='video.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('episode_num', models.CharField(max_length=500, null=True)),
                ('video_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='video.Video')),
            ],
            options={
                'db_table': 'Episode',
            },
        ),
    ]
