# Generated by Django 3.0 on 2020-03-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='animename',
        ),
        migrations.RemoveField(
            model_name='video',
            name='episode',
        ),
    ]
