# Generated by Django 3.0 on 2019-12-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20191215_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
        migrations.AddField(
            model_name='banner',
            name='cover_url',
            field=models.URLField(max_length=500, null=True, verbose_name='封面URL'),
        ),
    ]
