# Generated by Django 3.0 on 2019-12-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20191219_1045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeShip',
        ),
    ]
