# Generated by Django 3.0 on 2020-03-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20200328_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
