# Generated by Django 3.0 on 2020-03-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_delete_likeship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('episode_num', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'Episode',
            },
        ),
    ]
