# Generated by Django 3.0 on 2020-03-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_episode_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AlterField(
            model_name='episode',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='剧集链接 暂时弃用'),
        ),
    ]
