# Generated by Django 3.0 on 2019-12-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20191216_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='animename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='episode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
