# Generated by Django 3.0 on 2020-03-27 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='episode',
        ),
        migrations.AddField(
            model_name='episode',
            name='video_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
            preserve_default=False,
        ),
    ]
