# Generated by Django 3.0 on 2020-03-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20200327_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='video.Video'),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('videos', models.ManyToManyField(db_table='TypeToVideo', related_name='type', to='video.Video')),
            ],
        ),
    ]
