# Generated by Django 3.0 on 2019-12-16 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20191216_0901'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='videoname',
            table='AnimeName',
        ),
    ]
