# Generated by Django 3.0 on 2020-03-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20200328_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='videos',
            field=models.ManyToManyField(blank=True, db_table='TypeToVideo', related_name='type', to='video.Video'),
        ),
    ]
