# Generated by Django 3.0 on 2019-12-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20191216_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='brief',
            field=models.TextField(default=None, null=True),
        ),
    ]
