# Generated by Django 3.0 on 2020-03-28 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20200328_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.Classification'),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('videos', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='director', to='video.Video')),
            ],
            options={
                'db_table': 'Director',
            },
        ),
    ]
