# Generated by Django 3.0 on 2019-12-17 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0007_auto_20191216_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Viewer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
