# Generated by Django 3.0 on 2019-12-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': '视频操作数', 'verbose_name_plural': '视频操作数'},
        ),
        migrations.AlterModelTable(
            name='favorite',
            table='Fav',
        ),
    ]
