# Generated by Django 3.0 on 2020-03-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20200328_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='videos',
        ),
        migrations.AddField(
            model_name='video',
            name='director',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='production', to='video.Director'),
            preserve_default=False,
        ),
    ]
