# Generated by Django 3.0 on 2019-12-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20191217_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
