# Generated by Django 3.0 on 2019-12-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_favorite_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
