# Generated by Django 3.0 on 2019-12-17 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0011_auto_20191217_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='like',
        ),
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(default=0, related_name='_video_like_+', to=settings.AUTH_USER_MODEL, verbose_name='点赞数'),
        ),
    ]
