# Generated by Django 3.0 on 2019-12-18 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0012_auto_20191217_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(default=0, null=True, related_name='_video_like_+', to=settings.AUTH_USER_MODEL, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
