# Generated by Django 3.0 on 2019-12-18 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0014_auto_20191218_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_instance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('video_instance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='video.Video')),
            ],
        ),
    ]
